language: node_js

install:
  - npm install -g codecov

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

jobs:
  include:
    - stage: coverage
      node_js: "6"
      script:
      - npm run cover
      - codecov
