language: node_js
install:
  - npm install -g codecov
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

jobs:
  include:
    - stage: coverage
      node_js: "6"
      script:
      - npm run cover
      - ./node_modules/.bin/codecov
    - stage: npm release
      node_js: "6"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
